obstacle_range: 1.0
raytrace_range: 1.5

# Obstacle Cost Shaping (http://wiki.ros.org/costmap_2d/hydro/inflation)
# distance a circular robot should be clear of the obstacle
robot_radius: 0.2 
# if the robot is not circular
# footprint: [[x0, y0], [x1, y1], ... [xn, yn]] 
# max. distance from an obstacle at which costs are incurred for
# planning paths.
inflation_radius: 0.50  
# exponential rate at which the obstacle cost drops off (default: 10)
cost_scaling_factor: 5  

# voxel map configuration; z-voxels 0 are filled by bumpers and 1 by
# laser scan (kinect)
map_type: voxel
origin_z: 0.0
z_resolution: 0.2
z_voxels: 2
publish_voxel_map: false

observation_sources: scan bump
#observation_sources: scan

# scan: {
#        data_type: LaserScan, 
#        topic: scan, 
#        marking: true, 
#        clearing: true, 
#        min_obstacle_height: 0.25, 
#        max_obstacle_height: 0.35
#        }
# Our lasers (Xtion and fake) either needs to publish a height,
# or set min_obstacle_height to 0.0:
# http://wiki.ros.org/navigation/Troubleshooting#Missing_Obstacles_in_Costmap2D
# Note that the max_obstacle_height is very important too!
scan: {
        data_type: LaserScan,
        topic: my_robot/laser/scan,
        marking: true,
        clearing: true,
        min_obstacle_height: 0.0,
        max_obstacle_height: 3
      }
# Can we just set up two of these here?
#bump: {
#        data_type: PointCloud2, 
#        topic: mobile_base/sensors/bumper_pointcloud, 
#        marking: true, 
#        clearing: false, 
#        min_obstacle_height: 0.0, 
#        max_obstacle_height: 0.15
#      }
